name: linter

on: push

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "td1 td2 td3 td4"
          use-pylint: true
          use-pycodestyle: true
          use-flake8: true
          use-black: true
          use-mypy: true
          use-isort: true
